// export const en = {
//     // homepage
//     homePage:{
//         selectCategory:`Select Category`,
//         welcomeBack:`Welcome Back`,
//         selectLanguage:`Select Language`,
//         search:`Search`,
//         tableHeader:{
//             name:`Name`,
//             description:`Description`,
//             contentType:`Content Type`,
//             supporter:`Supporter`,
//             faculty:`Facaulty`,

//         }
//     },
//     // cases dynamic page
//     casesDynamicPage:{
//         medicalCaseNotFound:"Medical case not found",
//         forgotToAddPatient:`Woops - seems like you&apos;ve forgot to add a patient, please do so in Hygraph (The CMS)`,
//         patientCaseNotFound:`Patient case not found`,
//         somethingWentWrong:`Something went wrong, please try again or contact support.`,
//         patientDetails:`Patient Details`,
//         adjustmentsToDecisions:`Would you like to make any adjustments to your decisions?`,
//         addOrders:`Add Orders`,
//         proceed:`Proceed`,
//         restartMedicalCase:`Restart Medical Case`

//     }
// }


export const en = {
    tableHeader:{
                    name:`Name`,
                    description:`Description`,
                    contentType:`Content Type`,
                    supporter:`Supporter`,
                    faculty:`Faculty`,
        
                },
      english: "English",
      search:`Search`,
      german: "German",
      french: "French",
      patientDetails:`Patient Details`,
      years:"years",
      months:"months",
      selectLanguage:`Select Language`,
      forgotToAddPatient:`Woops - seems like you&apos;ve forgot to add a patient, please do so in Hygraph (The CMS)`,
      adjustmentsToDecisions:`Would you like to make any adjustments to your decisions?`,
      medicalCaseNotFound:"Medical case not found",
      webinarVidoeNotFound:"Webinar Video not found ",
      selectCategory: "Select Category",
      allCategories: "All Categories",
      patientCaseNotFound:`Patient case not found`,
      somethingWentWrong:`Something went wrong, please try again or contact support.`,
      name: "Name",
      action:"Action",
      caseDescription: "Case Description",
      time: "Time",
      supporter: "Supporter",
      faculty: "Faculty",
      restartMedicalCase: "restart medical case",
      demographics: "demographics",
      visits: "visits",
      tests: "Tests",
      test:"test",
      order:"order",
      remove:"Remove",
      add:"Add",
      view:"view",
      ordered:"Ordered",
      viewResults:"View results",
      close:"Close",
      back:"Back",
      diagnoses: "Diagnoses",
      orders: "orders",
      orderCap:"Order",
      ordersCap:"Orders",
      
      bmi:"BMI",
      age: "Age",
      gender: "Gender",
      findings:"findings",
      weight: "Weight",
      height: "Height",
      allergies: "Allergies",
      noPreviousTests:"no previous tests",
      pastVisits: "Past Visits",
      labsImaging: "Labs/Imaging",
      pastOrders: "Past Orders",
      introduction: "Introduction",
      consultation: "Consultation",
      patientInterview:"PatientInterview",
      selectAppropriateTests: "Select appropriate tests for the patient.",
      selectBestDiagnoses: "Select the best diagnoses.",
      existingDiagnoses: "Existing Diagnoses",
      medicationGuide: "Medication Guide",
      medication:"medication",
      medications:"medications",
      welcomeBack:`Welcome Back`,
selectRationales:"Select Rationales",
      noVideo:"There is no video to be displayed.",
      rr:"RR",
      kg:"KG",
    date:"date",
    drugInformationText:
      "Drug information is provided based on clinical guidelines and current research. Please refer to the package insert or summary of product characteristics, validated sources of product information, and clinical guidelines for further guidance.",
    gotIt: "Got it",
    selectAnOption:"select an Option",
    noPastDiagnoses:"No past diagnoses",
    treatmentPlans: "Treatment Plans",
    treatment:"Treatment",
   
    adjustMedications:
      "What adjustments, if any, would you make to the patient’s existing medications?",
    applySelections: "Apply selections",
    addMedications: "Add Medications",
    toProceedToNextPage:"to proceed to the next page.",
    dontSelectAnyMedicationToProceed:"Please don't select any medication to proceed to the next page.",
    addNonMedicationOrders: "Add Non-Medication Orders",
    pleaseSelect:"Please select",
    selectOneMedication:
      "Please select 1 medication to proceed to the next page.",
    selectAdditionalOrders:
      "Select appropriate additional orders for the patient.",
    consistentWithGuidance: "This is consistent with the guidance",
    inconsistentWithGuidance: "This is inconsistent with the guidance",
    lessOptimal:"This is less optimal according to the guidance",
    beforeProceeding: "Before you proceed",
    adjustDecisions: "Would you like to make any adjustments to your decisions?",
    addOrders: "Add orders",
    providedForYourBenefit:"Information provided for your benefit!",
    somethingDoesNotLookRight:`Hmm, something doesn't look right...`,
    proceed: "proceed",
    decisionReview: "Decision Review",
    clickToReview: "Click icons to review your decisions",
    reviewedDecisions: "Reviewed Decisions",
    caseReview: "Case Review",
    finish: "finish",
    continueToPostTest: "Continue to the post-test",
    next: "Next",
    noData:"no data",
    description: "Description",
    contentType: "Content Type",
    historyOfPresentIllness: "History of Present Illness",
    till:"Till",
    since:"Since",
    ongoing:"Ongoing",
   
    familyAndSocialHistory: "Family and Social History",
    physicalExamNotes: "Physical Examination Notes",
    startDate: "Start Date",
    endDate: "End Date",
    none:"none",
    noNewOrders: "No new orders",
    noPastOrders: "No past orders",
    newOrders: "New Orders",
    usefulnessQuestion:
      "How useful did you find this activity in enhancing your knowledge and skills for improving patient care in your clinical practice?",
    usefulnessScale: "0 = Not very useful 10 = Very useful",
    thankYou:
      "Thank you for participating in this activity. On the next page, you will be redirected to our website for additional resources and information.",
    submit: "submit",
    continue:"Continue",
    disContinue:"Discontinue",
    clinicalGuidance:"Clinical Guidance",
    selectAppropriate:"Select appropriate additional orders for the patient.",
    decisions:"Decisions",
    clickIcons:"Click icons to review your decisions",
    DecisionReview:"DecisionReview",
    CaseReview:"CaseReview",
    summary:"Summary",
    closingRemarks:"Closing Remarks",
    literatureReview:"Literature Review",
    references:"References",
    
  };
  