// export const fr = {
//     // homepage
//     homePage:{
//         selectCategory:`Sélectionnez une catégorie`,
//         welcomeBack:`Content de te revoir`,
//         selectLanguage:`Sélectionnez la langue`,
//         search:`recherche`,
//         tableHeader:{
//             name:`Nom`,
//             description:`Description`,
//             contentType:`Type de contenu`,
//             supporter:`Supporter`,
//             faculty:`Faculté`,
            
//         }
//     },
// // cases dynamic page
// casesDynamicPage:{
// medicalCaseNotFound:`Cas médical introuvable`,
// forgotToAddPatient:`Oups ! On dirait que vous avez oublié d'ajouter un patient. Veuillez le faire dans Hygraph (le CMS).`,
// patientCaseNotFound:`Cas patient introuvable`,
// somethingWentWrong:`Une erreur s'est produite, veuillez réessayer ou contacter le support.`,
// patientDetails:`Détails du patient`,
// adjustmentsToDecisions:`Souhaitez-vous apporter des ajustements à vos décisions ?`,
// addOrders:`Ajouter des commandes`,
// proceed:"procéder",
// restartMedicalCase:`Redémarrer le dossier médical` 

// }

// }



export const fr = {
  tableHeader: {
    name: "Nom",
    description: "Description",
    contentType: "Type de contenu",
    supporter: "Supporter",
    faculty: "Faculté",
  },
  english: "Anglais",
  search: "Recherche",
  german: "Allemand",
  french: "Français",
  patientDetails: "Détails du patient",
  years: "ans",
  months: "mois",
  selectLanguage: "Sélectionner la langue",
  forgotToAddPatient:
    "Oups – il semble que vous ayez oublié d'ajouter un patient. Veuillez le faire dans Hygraph (le CMS).",
  adjustmentsToDecisions: "Souhaitez-vous apporter des ajustements à vos décisions ?",
  medicalCaseNotFound: "Cas médical introuvable",
  webinarVidoeNotFound:"Vidéo du webinaire non trouvée",
  selectCategory: "Sélectionnez une catégorie",
  allCategories: "Toutes les catégories",
  patientCaseNotFound: "Cas du patient introuvable",
  somethingWentWrong:
    "Une erreur s'est produite. Veuillez réessayer ou contacter le support.",
  name: "Nom",
  action: "Action",
  caseDescription: "Description du cas",
  time: "Temps",
  supporter: "Supporter",
  faculty: "Faculté",
  restartMedicalCase: "redémarrer le cas médical",
  demographics: "démographie",
  visits: "visites",
  tests: "Essais",
  test: "test",
  order: "ordre",
  remove: "Supprimer",
  add: "Ajouter",
  view: "voir",
  ordered: "Commandé",
  viewResults: "Voir les résultats",
  close: "fermer",
  back: "Retour",
  diagnoses: "diagnostics",
  orders: "ordres",
  orderCap: "Ordre",
  ordersCap: "Ordres",
  bmi: "IMC",
  age: "Âge",
  gender: "Genre",
  findings: "résultats",
  weight: "Poids",
  height: "Taille",
  allergies: "Allergies",
  noPreviousTests: "aucun test précédent",
  pastVisits: "Visites passées",
  labsImaging: "Laboratoires/Imagerie",
  pastOrders: "Commandes passées",
  introduction: "Introduction",
  consultation: "Consultation",
  patientInterview: "Entretien du patient",
  selectAppropriateTests: "Sélectionnez les tests appropriés pour le patient.",
  selectBestDiagnoses: "Sélectionnez les meilleurs diagnostics.",
  existingDiagnoses: "Diagnostics existants",
  medicationGuide: "Guide des médicaments",
  medication: "médicament",
  medications: "médicaments",
  welcomeBack: "Bon retour",
  selectRationales: "Sélectionner les justifications",
  noVideo: "Aucune vidéo à afficher.",
  rr: "RR",
  kg: "KG",
  date: "date",
  drugInformationText:
    "Les informations sur les médicaments sont fournies selon les directives cliniques et la recherche actuelle. Veuillez consulter la notice, les sources validées et les lignes directrices pour plus d'informations.",
  gotIt: "Compris",
  selectAnOption: "sélectionnez une option",
  noPastDiagnoses: "Aucun diagnostic précédent",
  treatmentPlans: "Plans de traitement",
  treatment: "Traitement",
  adjustMedications:
    "Quels ajustements, le cas échéant, apporteriez-vous aux médicaments existants du patient ?",
  applySelections: "Appliquer les sélections",
  addMedications: "Ajouter des médicaments",
  toProceedToNextPage: "pour passer à la page suivante.",
  dontSelectAnyMedicationToProceed:
    "Veuillez ne sélectionner aucun médicament pour continuer.",
  addNonMedicationOrders: "Ajouter des ordonnances non médicamenteuses",
  pleaseSelect: "Veuillez sélectionner",
  selectOneMedication:
    "Veuillez sélectionner un médicament pour passer à la page suivante.",
  selectAdditionalOrders:
    "Sélectionnez les commandes supplémentaires appropriées pour le patient.",
  consistentWithGuidance: "Ceci est conforme aux directives",
  inconsistentWithGuidance: "Ceci n’est pas conforme aux directives",
  lessOptimal: "Ceci est moins optimal selon les directives",
  beforeProceeding: "Avant de continuer",
  adjustDecisions: "Souhaitez-vous apporter des ajustements à vos décisions ?",
  addOrders: "Ajouter des ordonnances",
  providedForYourBenefit: "Informations fournies pour votre bénéfice !",
  somethingDoesNotLookRight: "Hmm, quelque chose ne semble pas correct…",
  proceed: "procéder",
  decisionReview: "Révision des décisions",
  clickToReview: "Cliquez sur les icônes pour revoir vos décisions",
  reviewedDecisions: "Décisions révisées",
  caseReview: "Révision du cas",
  finish: "terminer",
  continueToPostTest: "Continuer vers le post-test",
  next: "Suivant",
  noData: "aucune donnée",
  description: "Description",
  contentType: "Type de contenu",
  historyOfPresentIllness: "Histoire de la maladie actuelle",
  till: "Jusqu’à",
  since: "Depuis",
  ongoing: "En cours",
  familyAndSocialHistory: "Histoire familiale et sociale",
  physicalExamNotes: "Notes d'examen physique",
  startDate: "Date de début",
  endDate: "Date de fin",
  none: "aucun",
  noNewOrders: "Aucune nouvelle commande",
  noPastOrders: "Aucune commande précédente",
  newOrders: "Nouvelles commandes",
  usefulnessQuestion:
    "Dans quelle mesure avez-vous trouvé cette activité utile pour améliorer vos connaissances et compétences dans la pratique clinique ?",
  usefulnessScale: "0 = Pas très utile 10 = Très utile",
  thankYou:
    "Merci d'avoir participé à cette activité. Vous serez redirigé vers notre site Web pour plus de ressources et d'informations.",
  submit: "soumettre",
  continue: "Continuer",
  disContinue: "Arrêter",
  clinicalGuidance: "Directives cliniques",
  selectAppropriate:
    "Sélectionnez les ordonnances supplémentaires appropriées pour le patient.",
  decisions: "Décisions",
  clickIcons: "Cliquez sur les icônes pour revoir vos décisions",
  DecisionReview: "Révision des décisions",
  CaseReview: "Révision du cas",
  summary: "Résumé",
  closingRemarks: "Remarques finales",
  literatureReview: "Revue de la littérature",
  references: "Références",
};
